services:
  client:
    image: yolo/client:1.2.0    # Specific version
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

    networks:
      - ramsey-network

  backend:
    image: yolo/backend:1.2      # Minor version
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase

    networks:
      - ramsey-network

  mongo:
    image: mongo:6.0              
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    networks:
      - ramsey-network

volumes:
  mongo-data:


networks:
  ramsey-network:
    driver: bridge










