---
- name: Ansible playbook for app
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Clone repository from github
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_directory }}"
      tags: clone_repo

    - name: Set up containers for app
      block:
        - include_role:
            name: frontend
          tags: frontend

        - include_role:
            name: backend
          tags: backend
      tags: setup_containers


