---
- name: Ansible playbook for app
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Set up containers for app
      block:
        - include_role:
            name: frontend
          tags: frontend

        - include_role:
            name: backend
          tags: backend
      tags: setup_containers


