- block:
    - name: Set up container for backend
      docker_container:
        name: backend
        image: "{{ backend_image }}"
        state: started
        ports:
          - "5000:5000"
      tags: backend_container
  tags: backend