apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yolo/backend:1.2
        env:
        - name: MONGO_URL
          value: "mongodb://mongo:27017/mydatabase"
        ports:
        - containerPort: 5000
